version: '3'
services:
  api:
    container_name: go-api-template_api
    image: golang:1.13.8
    #  build:
    #    context: .
    #    dockerfile: Dockerfile-api
    # tty: true
    ports:
      - "5000:5000"
    volumes:
      - ../:/go/src/go-api-template
    working_dir: /go/src/go-api-template
    command: go run main.go

  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data:
    driver: local
